server:
  port: 10080

spring:
  profiles:
    active: alpha

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  flyway:
    enabled: true
    username: sa

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=Mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          batch-size: 200

  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace

